import Head from "next/head";
// import { useEffect } from "react";
import { useRouter } from "next/router";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const router = useRouter();

  // useEffect(() => {
  //   async function loadtables() {
  //     const res = await fetch("/api/setup", { method: "POST" });
  //     const data = await res.json();
  //     console.log(data.message);
  //   }
  //   loadtables();
  // }, []);

  const handleLogin = () => {
    router.push("/login");
  };

  const handleSignup = () => {
    router.push("/signup");
  };

  return (
    <>
      <Head>
        <title>TODO Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <header className={styles.header}>
            <h1 className={styles.title}>Welcome to Todo Application</h1>
            <div className={styles.authButtons}>
              <button className={styles.button} onClick={handleLogin}>
                Login
              </button>
              <button className={styles.button} onClick={handleSignup}>
                Signup
              </button>
            </div>
          </header>
          <main className={styles.main}>
            <p className={styles.description}>
              Manage your tasks efficiently and effectively with our Todo
              Application.
            </p>
          </main>
        </main>
        <footer className={styles.footer}></footer>
      </div>
    </>
  );
}
